version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
